variable "project" {}
variable "region" {}
variable "ami" {}
variable "type" {}
variable "max_size" {}
variable "min_size" {}
variable "desired_size" {}
variable "healthy_threshold" {}
variable "unhealthy_threshold" {}
variable "timeout" {}
variable "interval" {}
